name: Github Action No. 2

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      - name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
        id: deployment
        uses: actions/deploy-pages@v1
